-- SOLUTION NUCLÉAIRE : Recréer table entièrement
DROP TABLE IF EXISTS public.contacts;

CREATE TABLE public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous insert" 
ON public.contacts 
FOR INSERT 
TO anon
WITH CHECK (true);

CREATE POLICY "Enable read access for authenticated users" 
ON public.contacts 
FOR SELECT 
TO authenticated 
USING (true);

GRANT USAGE ON SCHEMA public TO anon;
GRANT INSERT, SELECT ON public.contacts TO anon;
GRANT ALL ON public.contacts TO authenticated;