-- ============= SOLUTION COMPLÈTE RLS SUPABASE =============
-- À exécuter dans l'éditeur SQL Supabase Dashboard

-- ÉTAPE 1: Réinitialiser la configuration
DROP TABLE IF EXISTS public.contacts;

-- ÉTAPE 2: Recréer la table avec configuration optimale
CREATE TABLE public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ÉTAPE 3: Activer RLS
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;

-- ÉTAPE 4: Créer politiques RLS correctes
-- Politique pour INSERT (permettre aux utilisateurs anonymes d'insérer)
CREATE POLICY "Allow anonymous insert" 
ON public.contacts 
FOR INSERT 
WITH CHECK (true);

-- Politique pour SELECT (permettre de voir les données - admin uniquement)
CREATE POLICY "Enable read access for authenticated users" 
ON public.contacts 
FOR SELECT 
USING (auth.role() = 'authenticated');

-- ÉTAPE 5: Donner les permissions nécessaires
GRANT USAGE ON SCHEMA public TO anon;
GRANT ALL ON public.contacts TO anon;
GRANT ALL ON public.contacts TO authenticated;

-- ÉTAPE 6: Validation
SELECT 
    schemaname,
    tablename,
    rowsecurity 
FROM pg_tables 
WHERE tablename = 'contacts';

SELECT 
    policyname,
    permissive,
    roles,
    cmd,
    qual,
    with_check
FROM pg_policies 
WHERE tablename = 'contacts';